module.exports = [
    "Harold solved enigma in five seconds, by himself.",
    "When Alexander Bell invented the telephone he had 3 missed calls from Harold",
    "Fear of spiders is aracnaphobia, fear of tight spaces is chlaustraphobia, fear of Harold is called Logic",
    "There used to be a street named after Harold, but it was changed because nobody crosses Harold and lives.",
    "Harold has already been to Mars; that's why there are no signs of life.",
    "Some magicans can walk on water, Harold can swim through land.",
    "Harold and Superman once fought each other on a bet. The loser had to start wearing his underwear on the outside of his pants.",
    "Harold once urinated in a semi truck's gas tank as a joke....that truck is now known as Optimus Prime.",
    "Harold counted to infinity - twice.",
    "Harold can cut through a hot knife with butter",
    "Harold is the reason why Waldo is hiding.",
    "Harold can slam a revolving door.",
    "Harold once kicked a horse in the chin. Its decendants are known today as Giraffes.",
    "Harold can win a game of Connect Four in only three moves.",
    "Harold doesn't call the wrong number. You answer the wrong phone.",
    "When Harold does a pushup, he isn't lifting himself up, he's pushing the Earth down.",
    "Harold can light a fire by rubbing two ice-cubes together.",
    "Harold doesn’t wear a watch. HE decides what time it is.",
    "Harold’ PC doesn’t have a Recycle bin – because when Harold deletes something, there’s no chance of it coming back.",
    "Some people wear Superman pajamas. Superman wears Harold pajamas.",
    "Harold won the World Series of Poker using Pokemon cards",
    "If you spell Harold in Scrabble, you win. Forever.",
    "Harold destroyed the periodic table, because Harold only recognizes the element of surprise.",
    "Harold' hand is the only hand that can beat a Royal Flush.",
    "Harold bit the Apple logo",
    "Harold flew his first paper airplane when he was 4 years old. It landed yesterday.",
    "Harold played Russian Roulette with a fully loaded gun and won.",
    "Harold got UNO while playing Texas hold 'em.",
    "Harold once made a snowman...out of rain.",
    "When Harold throws exceptions, it’s across the room.",
    "All arrays Harold declares are of infinite size, because Harold knows no bounds.",
    "Harold doesn’t have disk latency because the hard drive knows to hurry the hell up.",
    "Harold writes code that optimizes itself.",
    "Harold can’t test for equality because he has no equal.",
    "Harold doesn’t need garbage collection because he doesn’t call .Dispose(), he calls .DropKick().",
    "Harold’s first program was kill -9.",
    "Harold burst the dot com bubble.",
    "All browsers support the hex definitions #harold and #liss for the colors black and blue.",
    "Harold can write infinite recursion functions…and have them return.",
    "Harold can solve the Towers of Hanoi in one move.",
    "Harold finished World of Warcraft.",
    "Project managers never ask Harold for estimations…ever.",
    "Harold doesn’t use web standards as the web will conform to him.",
    "“It works on my machine” always holds true for Harold.",
    "Whiteboards are white because Harold scared them that way.",
    "Harold doesn’t do Burn Down charts, he does Smack Down charts.",
    "Harold's calendar goes straight from March 31st to April 2nd; no one fools Harold.",
    "Harold can stand at the bottom of a bottomless pit.",
    "Harold can delete the Recycling Bin.",
    "Harold can unit test entire applications with a single assert.",
    "Harold doesn’t bug hunt as that signifies a probability of failure, he goes bug killing.",
    "Harold’s keyboard doesn’t have a Ctrl key because nothing controls Harold.",
    "When Harold is web surfing websites get the message “Warning: Internet Explorer has deemed this user to be malicious or dangerous. Proceed?”.",
    "Harold can recite pi. Backwards",
    "Harold won the lifetime achievement award--twice."
];
