module.exports = [
    "Harold solved enigma in five seconds, by himself.",
    "When Alexander Bell invented the telephone he had 3 missed calls from Harold",
    "Fear of spiders is aracnaphobia, fear of tight spaces is chlaustraphobia, fear of Harold is called Logic",
    "There used to be a street named after Harold, but it was changed because nobody crosses Harold and lives.",
    "Harold died 20 years ago, Death just hasn't built up the courage to tell him yet.",
    "If you rate this 5 roundhouse kicks, then Harold WILL roundhouse kick Justin Bieber's ass.",
    "Harold has already been to Mars; that's why there are no signs of life.",
    "Some magicans can walk on water, Harold can swim through land.",
    "Harold and Superman once fought each other on a bet. The loser had to start wearing his underwear on the outside of his pants.",
    "Harold once urinated in a semi truck's gas tank as a joke....that truck is now known as Optimus Prime.",
    "Harold counted to infinity - twice.",
    "Harold can cut through a hot knife with butter",
    "Harold doesn't flush the toilet, he scares the sh*t out of it",
    "Harold is the reason why Waldo is hiding.",
    "Death once had a near-Harold experience",
    "Harold has a grizzly bear carpet in his room. The bear isn't dead it is just afriad to move.",
    "Harold can slam a revolving door.",
    "When the Boogeyman goes to sleep every night, he checks his closet for Harold.",
    "Harold once kicked a horse in the chin. Its decendants are known today as Giraffes.",
    "Harold will never have a heart attack. His heart isn't nearly foolish enough to attack him.",
    "Harold can win a game of Connect Four in only three moves.",
    "Harold doesn't call the wrong number. You answer the wrong phone.",
    "Harold once got bit by a rattle snake........ After three days of pain and agony ..................the rattle snake died",
    "When Harold does a pushup, he isn't lifting himself up, he's pushing the Earth down.",
    "There is no theory of evolution. Just a list of animals Harold allows to live.",
    "Harold can light a fire by rubbing two ice-cubes together.",
    "Harold doesn’t wear a watch. HE decides what time it is.",
    "The original title for Alien vs. Predator was Alien and Predator vs Harold.",
    "The film was cancelled shortly after going into preproduction. No one would pay nine dollars to see a movie fourteen seconds long.",
    "Harold doesn't read books. He stares them down until he gets the information he wants.",
    "Harold made a Happy Meal cry.",
    "Harold’ PC doesn’t have a Recycle bin – because when Harold deletes something, there’s no chance of it coming back.",
    "Some people wear Superman pajamas. Superman wears Harold pajamas.",
    "Harold won the World Series of Poker using Pokemon cards",
    "If you spell Harold in Scrabble, you win. Forever.",
    "Outer space exists because it's afraid to be on the same planet with Harold.",
    "They once made a Harold toilet paper, but there was a problem: It wouldn't take shit from anybody.",
    "Harold destroyed the periodic table, because Harold only recognizes the element of surprise.",
    "Harold' hand is the only hand that can beat a Royal Flush.",
    "Harold was ordered to go to court once but the judge never showed up.",
    "Harold was supposed to play the lead role in Mission: Impossible. He was replaced by Tom Cruise because the tittle wouldn't make any sense.",
    "According to Einstein's theory of relativity, Harold can actually roundhouse kick you yesterday.",
    "Harold bit the Apple logo",
    "Harold doesn't mow his lawn, he stands on the porch and dares it to grow",
    "Every time Harold looks into a mirror it breaks. Even glass is not stupid enough to get between Harold and Harold.",
    "Harold can strangle you with a cordless phone.",
    "Harold flew his first paper airplane when he was 4 years old. It landed yesterday.",
    "Harold played Russian Roulette with a fully loaded gun and won.",
    "Harold got UNO while playing Texas hold 'em.",
    "Harold once made a snowman...out of rain.",
    "Steven Spielberg would have cast Harold in Jaws, but it would have been a 2 hour documentary about sushi."
];
